#!/usr/bin/perl 

use strict;
use warnings;
use Data::Dumper qw(Dumper);

my $file = $ARGV[0];
my $addLength = $ARGV[1];

my @temp = split(/\./,$file);

my $outFile = $temp[2]."."."BedIndexFromMerge.bed";



open(READ,$file) || die "Could not open $file,$!";
open(OUT,">",$outFile) || die "Coult not create $outFile $!";

my $start = 0;
my $stop;
my $chrPointerOld = "chr1";


while (<READ>) {
	chomp;

	my @line = split("\t",$_);

	my $chrPointer = $line[0];

	if ($chrPointer ne $chrPointerOld) {
		
		$start = 0;
	}
	
	my $featureLength = $line[2]-$line[1];

	$start = $start + $addLength;
	$stop = $start + $featureLength;

	my $newline = $line[0]."\t".$start."\t".$stop."\t".$line[3];

	print OUT "$newline\n";

	$start = $stop;
	$stop = 0;
	$chrPointerOld = $chrPointer;

}

print "Done!\n";